import sqlite3 as lite
con = lite.connect('db.sqlite3')


def cat_schema():
    with con:
        cur = con.cursor()
        cur.execute("""
            CREATE TABLE IF NOT EXISTS cat_schema(
                id INTEGER PRIMARY KEY, cats TEXT, rarity TEXT, cat_one TEXT,
                cat_two TEXT
                );
                """)
        cur.close()
    with con:
        cur = con.cursor()
        cur.execute("""
            INSERT INTO cat_schema(id, cats, rarity, cat_one, cat_two)
                        VALUES (NULL, "black_cat", "egg", "none", "none"),
                                (NULL, "gray_cat", "egg", "none", "none"),
                                (NULL, "chocolate_cat", "egg", "none", "none"),
                                (NULL, "chocolate_cat", "egg", "none", "none"),
                                (NULL, "lilac_cat", "egg", "none", "none"),
                                (NULL, "cinnamon_cat", "egg", "none", "none"),
                                (NULL, "fawn_cat", "egg", "none", "none"),
                                (NULL, "ginger_cat", "egg", "none", "none"),
                                (NULL, "cream_cat", "egg", "none", "none"),
                                (NULL, "apricot_cat", "egg", "none", "none"),
                                (NULL, "white_cat", "egg", "none", "none"),
                                (NULL, "albino_cat", "egg", "none", "none"),
                                (NULL, "silver", "super", "black_cat", "white_cat"),
                                (NULL, "silver", "super", "gray_cat", "gray_cat"),
                                (NULL, "silver", "super", "white_cat", "black_cat"),
                                (NULL, "silver", "super", "black_cat", "gray_cat"),
                                (NULL, "brown_tabby", "super", "chocolate_cat", "black_cat"),
                                (NULL, "tortie", "super", "black_cat", "ginger_cat"),
                                (NULL, "tortie", "super", "ginger_cat", "black_cat"),
                                (NULL, "black_smoke", "super", "black_cat", "white_cat"),
                                (NULL, "black_smoke", "super", "white_cat", "black_cat"),
                                (NULL, "gray_tabby", "super", "gray_cat", "black_cat"),
                                (NULL, "blue_mink", "super", "gray_cat", "gray_cat"),
                                (NULL, "blue_sepia", "super", "gray_cat", "gray_cat"),
                                (NULL, "blue_tabby", "super", "lilac_cat", "gray_cat"),
                                (NULL, "blue_tabby", "super", "gray_cat", "lilac_cat"),
                                (NULL, "cream_tortie", "super", "gray_cat", "cream_cat"),
                                (NULL, "cream_tortie", "super", "cream_cat", "gray_cat"),
                                (NULL, "blue_smoke", "super", "gray_cat", "white_cat"),
                                (NULL, "blue_smoke", "super", "white_cat", "gray_cat"),
                                (NULL, "blue_point", "super", "gray_cat", "white_cat"),
                                (NULL, "blue_point", "super", "white_cat", "gray_cat"),
                                (NULL, "chocolate_mink", "super", "chocolate_cat", "chocolate_cat"),
                                (NULL, "chocolate_sepia", "super", "chocolate_cat", "chocolate_cat"),
                                (NULL, "lilac_tabby", "super", "lilac_cat", "chocolate_cat"),
                                (NULL, "lilac_tabby", "super", "chocolate_cat","lilac_cat"),
                                (NULL, "lilac_point", "super", "lilac_cat", "chocolate_cat"),
                                (NULL, "seal_point", "super", "chocolate_cat","lilac_cat"),
                                (NULL, "chocolate_tortie", "super", "ginger_cat", "chocolate_cat"),
                                (NULL, "chocolate_tortie", "super", "chocolate_cat", "ginger_cat"),
                                (NULL, "chocolate_point", "super", "chocolate_cat", "cream_cat"),
                                (NULL, "chocolate_point", "super", "cream_cat", "chocolate_cat"),
                                (NULL, "chocolate_smoke", "super", "chocolate_cat", "white_cat"),
                                (NULL, "chocolate_smoke", "super", "white_cat", "chocolate_cat"),
                                (NULL, "lilac_cream_tortie", "super", "lilac_cat", "cream_cat"),
                                (NULL, "lilac_cream_tortie", "super", "cream_cat", "lilac_cat"),
                                (NULL, "lilac_smoke", "super", "lilac_cat", "white_cat"),
                                (NULL, "lilac_smoke", "super", "white_cat", "lilac_cat"),
                                (NULL, "cinnamon_mink", "super", "cinnamon_cat", "cinnamon_cat"),
                                (NULL, "cinnamon_sepia", "super", "cinnamon_cat", "cinnamon_cat"),
                                (NULL, "cinnamon_tabby", "super", "cinnamon_cat", "fawn_cat"),
                                (NULL, "cinnamon_tabby", "super", "fawn_cat", "cinnamon_cat"),
                                (NULL, "fawn_tabby", "super", "cinnamon_cat", "fawn_cat"),
                                (NULL, "fawn_tabby", "super", "fawn_cat", "cinnamon_cat"),
                                (NULL, "cinnamon_tortie", "super", "ginger_cat", "cinnamon_cat"),
                                (NULL, "cinnamon_tortie", "super", "cinnamon_cat", "ginger_cat"),
                                (NULL, "cinnamon_point", "super", "cinnamon_cat", "cream_cat"),
                                (NULL, "cinnamon_point", "super", "cream_cat", "cinnamon_cat"),
                                (NULL, "cinnamon_smoke", "super", "cinnamon_cat", "white_cat"),
                                (NULL, "cinnamon_smoke", "super", "white_cat", "cinnamon_cat"),
                                (NULL, "fawn_mink", "super", "fawn_cat", "fawn_cat"),
                                (NULL, "fawn_sepia", "super", "fawn_cat", "fawn_cat"),
                                (NULL, "fawn_point", "super", "fawn_cat", "cream_cat"),
                                (NULL, "fawn_point", "super", "cream_cat", "fawn_cat"),
                                (NULL, "fawn_cream_tortie", "super", "fawn_cat", "cream_cat"),
                                (NULL, "fawn_cream_tortie", "super", "cream_cat", "fawn_cat"),
                                (NULL, "fawn_smoke", "super", "fawn_cat", "white_cat"),
                                (NULL, "fawn smoke", "super", "white_cat", "fawn_cat"),
                                (NULL, "red_tabby", "super", "ginger_cat", "cream_cat"),
                                (NULL, "red_tabby", "super", "ginger_cat", "apricot_cat"),
                                (NULL, "red_tabby", "super", "cream_cat", "ginger_cat"),
                                (NULL, "red_tabby", "super", "apricot_cat", "ginger_cat"),
                                (NULL, "flame_point", "super", "ginger_cat", "cream_cat"),
                                (NULL, "flame_point", "super", "ginger_cat", "apricot_cat"),
                                (NULL, "flame_point", "super", "cream_cat", "ginger_cat"),
                                (NULL, "flame_point", "super", "apricot_cat", "ginger_cat"),
                                (NULL, "flame_mink", "super", "ginger_cat", "cream_cat"),
                                (NULL, "flame_mink", "super", "ginger_cat", "apricot_cat"),
                                (NULL, "flame_mink", "super", "cream_cat", "ginger_cat"),
                                (NULL, "flame_mink", "super", "apricot_cat", "ginger_cat"),
                                (NULL, "flame_sepia", "super", "ginger_cat", "cream_cat"),
                                (NULL, "flame_sepia", "super", "ginger_cat", "apricot_cat"),
                                (NULL, "flame_sepia", "super", "cream_cat", "ginger_cat"),
                                (NULL, "flame_sepia", "super", "apricot_cat", "ginger_cat"),
                                (NULL, "cream_tabby", "super", "cream_cat", "ginger_cat"),
                                (NULL, "cream_point", "super", "cream_cat", "ginger_cat"),
                                (NULL, "cream_mink", "super", "cream_cat", "ginger_cat"),
                                (NULL, "cream_sepia", "super", "cream_cat", "ginger_cat"),
                                (NULL, "cream_tabby", "super", "cream_cat", "apricot_cat"),
                                (NULL, "cream_point", "super", "cream_cat", "apricot_cat"),
                                (NULL, "cream_mink", "super", "cream_cat", "apricot_cat"),
                                (NULL, "cream_sepia", "super", "cream_cat", "apricot_cat"),
                                (NULL, "cream_tabby", "super", "apricot_cat", "cream_cat"),
                                (NULL, "cream_point", "super", "apricot_cat", "cream_cat"),
                                (NULL, "cream_mink", "super", "apricot_cat", "cream_cat"),
                                (NULL, "cream_sepia", "super", "apricot_cat", "cream_cat"),
                                (NULL, "cameo_tabby", "super", "white_cat", "ginger_cat"),
                                (NULL, "cameo_tabby", "super", "ginger_cat", "white_cat"),
                                (NULL, "red_smoke", "super", "white_cat", "ginger_cat"),
                                (NULL, "red_smoke", "super", "ginger_cat", "white_cat"),
                                (NULL, "cream_cameo_tabby", "super", "cream_cat", "white_cat"),
                                (NULL, "cream_cameo_tabby", "super", "white_cat", "cream_cat"),
                                (NULL, "cream_smoke", "super", "cream_cat", "white_cat"),
                                (NULL, "cream_smoke", "super", "white_cat", "cream_cat"),
                                (NULL, "canvas_cat", "super", "albino_cat", "albino_cat"),
                                (NULL, "silver_tabby", "legendary", "silver", "black_cat"),
                                (NULL, "silver_tabby", "legendary", "black_cat", "silver"),
                                (NULL, "blue_silver_tabby", "legendary", "silver", "gray_cat"),
                                (NULL, "blue_silver_tabby", "legendary", "gray_cat", "silver_tabby"),
                                (NULL, "gray_lynx_point", "legendary", "gray_tabby", "gray_cat"),
                                (NULL, "gray_lynx_point", "legendary", "gray_cat", "gray_tabby"),
                                (NULL, "blue_lynx_point", "legendary", "blue_tabby", "gray_cat"),
                                (NULL, "blue_lynx_point", "legendary", "gray_cat", "blue_tabby"),
                                (NULL, "chocolate_silver_tabby", "legendary", "silver", "chocolate_cat"),
                                (NULL, "chocolate_silver_tabby", "legendary", "chocolate_cat", "silver"),
                                (NULL, "lilac_silver_tabby", "legendary", "silver", "lilac_cat"),
                                (NULL, "lilac_silver_tabby", "legendary", "lilac_cat", "silver"),
                                (NULL, "cinnamon_silver_tabby", "legendary", "silver", "cinnamon_cat"),
                                (NULL, "cinnamon_silver_tabby", "legendary", "cinnamon_cat", "silver"),
                                (NULL, "fawn_silver_tabby", "legendary", "silver", "fawn_cat"),
                                (NULL, "fawn_silver_tabby", "legendary", "fawn_cat", "silver"),
                                (NULL, "red_silver_tabby", "legendary", "silver", "ginger_cat"),
                                (NULL, "red_silver_tabby", "legendary", "ginger_cat", "silver"),
                                (NULL, "cream_silver_tabby", "legendary", "silver", "cream_cat"),
                                (NULL, "cream_silver_tabby", "legendary", "cream_cat", "silver"),
                                (NULL, "brown_lynx_point", "legendary", "brown_tabby", "cream_cat"),
                                (NULL, "brown_lynx_point", "legendary", "cream_cat", "brown_tabby"),
                                (NULL, "lilac_lynx_point", "legendary", "lilac_tabby", "cream_cat"),
                                (NULL, "lilac_lynx_point", "legendary", "cream_cat", "lilac_tabby"),
                                (NULL, "cinnamon_lynx_point", "legendary", "cinnamon_tabby", "cream_cat"),
                                (NULL, "cinnamon_lynx_point", "legendary", "cream_cat", "cinnamon_tabby"),
                                (NULL, "fawn_lynx_point", "legendary", "fawn_tabby", "cream_cat"),
                                (NULL, "fawn_lynx_point", "legendary", "cream_cat", "fawn_tabby"),
                                (NULL, "red_lynx_point", "legendary", "red_tabby", "cream_cat"),
                                (NULL, "red_lynx_point", "legendary", "cream_cat", "red_tabby"),
                                (NULL, "cream_lynx_point", "legendary", "cream_tabby", "cream_cat"),
                                (NULL, "cream_lynx_point", "legendary", "cream_cat", "cream_tabby"),
                                (NULL, "cameo_lynx_point", "legendary", "cameo_tabby", "cream_cat"),
                                (NULL, "cameo_lynx_point", "legendary", "cream_cat", "cameo_tabby"),
                                (NULL, "cream_cameo_lynx_point", "legendary", "cream_cameo_tabby", "cream_cat"),
                                (NULL, "cream_cameo_lynx_point", "legendary", "cream_cat", "cream_cameo_tabby"),
                                (NULL, "brindled_tortie", "legendary", "tortie", "white_cat"),
                                (NULL, "brindled_tortie", "legendary", "white_cat", "tortie"),
                                (NULL, "brindled_cream_tortie", "legendary", "cream_tortie", "white_cat"),
                                (NULL, "brindled_cream_tortie", "legendary", "white_cat", "cream_tortie"),
                                (NULL, "brindled_chocolate_tortie", "legendary", "chocolate_tortie", "white_cat"),
                                (NULL, "brindled_chocolate_tortie", "legendary", "white_cat", "chocolate_tortie"),
                                (NULL, "brindled_cinnamon_tortie", "legendary", "cinnamon_tortie", "white_cat"),
                                (NULL, "brindled_cinnamon_tortie", "legendary", "white_cat", "cinnamon_tortie"),
                                (NULL, "brindled_lilac_tortie", "legendary", "lilac_cream_tortie", "white_cat"),
                                (NULL, "brindled_lilac_tortie", "legendary", "white_cat", "lilac_cream_tortie"),
                                (NULL, "brindled_fawn_tortie", "legendary", "fawn_cream_tortie", "white_cat"),
                                (NULL, "brindled_fawn_tortie", "legendary", "white_cat", "fawn_cream_tortie"),
                                (NULL, "chinchilla", "legendary", "silver", "white_cat")
                                ;

                """)
        cur.close()
